[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/about"
  to = "/about/"
  status = 301
  force = true

[[redirects]]
  from = "/about/*"
  to = "https://portfolio1-jade-ten.vercel.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  targetPort = 3000
