[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/about"
  to = "https://aikishor.live/about"
  status = 302
  force = true

[[redirects]]
  from = "/about/*"
  to = "https://aikishor.live/about/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  targetPort = 3000
